#pragma once

_GL_BEGIN
enum class OBJECT_TYPE : GLenum
{
	GLSL,
	REGULAR,
	CONTAINER,
	OTHER,
};

enum class DATA_TYPE : GLenum
{
	UNSIGNED_BYTE = GL_UNSIGNED_BYTE,
	UNSIGNED_INT = GL_UNSIGNED_INT,
	FLOAT = GL_FLOAT,
};

enum class BUFFER_TYPE : GLenum
{
	ARRAY_BUFFER = GL_ARRAY_BUFFER,
	ELEMENT_ARRAY_BUFFER = GL_ELEMENT_ARRAY_BUFFER,
};

enum class SHADER_TYPE : GLenum
{
	VERTEX = GL_VERTEX_SHADER,
	GEOMETRY = GL_GEOMETRY_SHADER,
	FRAGMENT = GL_FRAGMENT_SHADER,
};

enum class TEXTURE_TYPE : GLenum
{
	T1D = GL_TEXTURE_1D,
	T2D = GL_TEXTURE_2D,
};

enum class TEXTURE_FORMAT : GLenum
{
	RGB = GL_RGB,
	RGBA = GL_RGBA,
	BGRA = GL_BGRA,
};

enum class DRAW_MODE : GLenum
{
	POINTS = GL_POINTS,
	LINES = GL_LINES,
	LINE_LOOP = GL_LINE_LOOP,
	LINE_STRIP = GL_LINE_STRIP,
	TRIANGLES = GL_TRIANGLES,
	TRIANGLE_STRIP = GL_TRIANGLE_STRIP,
	TRIANGLE_FAN = GL_TRIANGLE_FAN,
	QUADS = GL_QUADS,
};
_GL_END